import "./globals.css";
import { Poppins } from "next/font/google";
import localFont from "next/font/local";
import Menubar from "./components/menubar/menubar";
import Footer from "./components/footer/footer";
import { config } from "@fortawesome/fontawesome-svg-core";
import "@fortawesome/fontawesome-svg-core/styles.css";
import { GlobalStateProvider } from "./utility/globalStateProvide";
import SmoothScrolling from "./SmoothScrolling";
import Providers from "./components/ProgressBarProvider/ProgressBarProvider";

config.autoAddCss = false;

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const poppins = Poppins({
  subsets: ["latin"],
  variable: "--font-poppins",
  weight: ["300", "400", "500", "600", "700"],
});

const cervino = localFont({
  src: [
    {
      path: "./fonts/Cervino-MediumNeue.woff",
      weight: "500",
      style: "normal",
    },
    {
      path: "./fonts/Cervino-SemiBoldNeue.woff",
      weight: "600",
      style: "normal",
    },
    {
      path: "./fonts/Cervino-BoldNeue.woff",
      weight: "700",
      style: "normal",
    },
    {
      path: "./fonts/Cervino-ExtraBoldNeue.woff",
      weight: "800",
      style: "normal",
    },
  ],
  variable: "--font-cervino",
});

export default function RootLayout({ children }) {
  return (
    <GlobalStateProvider>
      <html lang="en">
        <body className={`${poppins.className} ${cervino.variable}`}>
          <Providers>
            <Menubar />
            <SmoothScrolling>
              <div id="main">{children}</div>
            </SmoothScrolling>
            <Footer />
          </Providers>
        </body>
      </html>
    </GlobalStateProvider>
  );
}
